Area_Options = [
    "Please select the problem area",
    "3rd Party Apps",
    "Accessibility",
    "AirDrop",
    "AirPlay",
    "AirPods",
    "App Privacy Report",
    "App Store",
    "App Switcher",
    "Apple Intelligence",
    "Apple Pay",
    "Audio",
    "Auto Unlock",
    "Backup",
    "Battery Charging",
    "Battery Life",
    "Bluetooth",
    "Books",
    "Calculator",
    "Calendar",
    "Camera",
    "Car Keys",
    "CarPlay",
    "Cellular Service (Calls & Data)",
    "Clock",
    "Contacts",
    "Continuity/Handoff",
    "Control Center",
    "Device Feels Warm",
    "Device Syncing",
    "Face ID",
    "FaceTime",
    "FaceTime - SharePlay",
    "Feedback Assistant",
    "Files app",
    "Find My",
    "Fitness/Fitness+",
    "Focus",
    "Freeform",
    "Game Controller",
    "Haptics/Vibration",
    "Health",
    "Home App & HomeKit / Matter Accessories",
    "Home Screen",
    "iCloud",
    "Image Playground",
    "iTunes Store",
    "Journal",
    "Keyboard",
    "Lock Screen",
    "Mail",
    "Maps",
    "Messages",
    "Music",
    "Music Classical",
    "News",
    "Notes",
    "Notification Center",
    "Notifications",
    "Passwords",
    "Phone app",
    "Photos",
    "Picture in Picture",
    "Podcasts",
    "Printing",
    "Reminders",
    "Rotation",
    "Safari",
    "Safety Check",
    "Screen Recording",
    "Screen Time",
    "Scribble",
    "Security",
    "Settings",
    "Share Sheet",
    "Shortcuts",
    "Sidecar",
    "Siri",
    "Sleep",
    "Software Update",
    "Split View/Drag and Drop",
    "Spotlight Search",
    "Stage Manager",
    "StandBy",
    "System Crashes",
    "System Slow/Unresponsive",
    "Touch ID",
    "Translate app",
    "Translation/Localization",
    "TV app/Apple TV+",
    "VPN",
    "Wallet",
    "Wallpaper",
    "Watch app",
    "Weather",
    "Wi-Fi",
    "Something else not on this list"]

Type_Options = [
    "Incorrect/Unexpected Behavior",
    "Application Crash",
    "Application Slow/Unresponsive",
    "Battery Life",
    "Suggestion"
]