name: Updated Build Number [Automatic]

on:
  push:
    branches:
      - main

jobs:
  increment_build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Build Number
        run: |
          PLIST_FILE="swift/Feedback-X-Info.plist"
          
          # CFBundleShortVersionString (Stored as a String)
          if ! /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_FILE"; then
            echo "CFBundleShortVersionString does not exist. Setting it to '1.0'."
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string '1.0'" "$PLIST_FILE"
            CURRENT_VERSION="1.0"
          else
            CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_FILE")
          fi

          # Extract major version (before ".") and increment
          VERSION_PARTS=(${CURRENT_VERSION//./ }) # Split by '.'
          MAJOR_VERSION=${VERSION_PARTS[0]}
          NEW_VERSION="$((MAJOR_VERSION + 1)).0"

          # Update CFBundleShortVersionString as a string
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString '$NEW_VERSION'" "$PLIST_FILE"
          echo "Updated CFBundleShortVersionString to $NEW_VERSION"

          # CFBundleVersion (Stored as an Integer)
          if ! /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_FILE"; then
            echo "CFBundleVersion does not exist. Setting it to 1."
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion integer 1" "$PLIST_FILE"
            CURRENT_BUILD_NUMBER=1
          else
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_FILE")
          fi
          
          NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))

          # Update CFBundleVersion as an integer
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$PLIST_FILE"
          echo "Updated CFBundleVersion to $NEW_BUILD_NUMBER"

      - name: Pull latest changes
        run: |
          git fetch origin
          git pull origin main

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use the Personal Access Token (PAT) to authenticate
          git add swift/Feedback-X-Info.plist
          git commit -m "Auto-incremented build number to $NEW_BUILD_NUMBER and version to $NEW_VERSION"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/LeonHTM/Feedback-X.git
