name: Updated Build Number [Automatic]

on:
  push:
    branches:
      - main

jobs:
  increment_build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Build Number
        run: |
          PLIST_FILE="swift/Feedback-X-Info.plist"
          
          # Check if CFBundleShortVersionString exists, if not, initialize it
          if ! /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_FILE"; then
            echo "CFBundleShortVersionString does not exist. Setting it to 1."
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString integer 1" "$PLIST_FILE"
            CURRENT_BUILD_NUMBER=1
          else
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST_FILE")
          fi
          
          NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
          
          # Update CFBundleShortVersionString without adding a new string entry
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_BUILD_NUMBER" "$PLIST_FILE"
          echo "Updated build number to $NEW_BUILD_NUMBER"

      - name: Pull latest changes
        run: |
          git fetch origin
          git pull origin main

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use the Personal Access Token (PAT) to authenticate
          git add swift/Feedback-X-Info.plist
          git commit -m "Auto-incremented build number to $NEW_BUILD_NUMBER"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/LeonHTM/Feedback-X.git
