name: Auto Increment Build Number

on:
  push:
    branches:
      - main

jobs:
  increment_build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Increment build number
        run: |
          PLIST_FILE="swift/Feedback-X-Info.plist"
          
          # Check if CFBundleVersion exists, if not, initialize it
          if ! /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_FILE"; then
            echo "CFBundleVersion does not exist. Setting it to 1."
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion integer 1" "$PLIST_FILE"
            CURRENT_BUILD_NUMBER=1
          else
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST_FILE")
          fi
          
          NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
          
          # Update CFBundleVersion without adding a new string entry
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$PLIST_FILE"
          echo "Updated build number to $NEW_BUILD_NUMBER"

      - name: Fetch and merge latest changes
        run: |
          git fetch origin
          git reset --hard origin/main
          git merge origin/main --no-edit

      - name: Commit and push changes (if needed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are changes before committing
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit, skipping push."
            exit 0  # Exit successfully
          fi

          # Add, commit, and push only if there are changes
          git add swift/Feedback-X-Info.plist
          git commit -m "Auto-incremented build number to $NEW_BUILD_NUMBER"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/LeonHTM/Feedback-X.git
